|||||100+++++
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace (nombreSistema).Model
{
    public class (nombreTabla)ParamGenerated : BaseParam
    {

        public (nombreTabla)ParamGenerated():base()
        {

        }

        public (nombreTabla)ParamGenerated(BaseParam baseParam): this(baseParam.P_empresaid, baseParam.P_sucursalid)
        {
            
        }
        public (nombreTabla)ParamGenerated(long? empresaid, long? sucursalid) : base(empresaid, sucursalid)
        {
		|||||110+++++
		this.(nombreCampoCapitalizado) = "";
		|||||120+++++
		this.(nombreCampoCapitalizado) = "N";
		|||||130+++++
		this.(nombreCampoCapitalizado) = 0.0m;
		|||||140+++++
		this.(nombreCampoCapitalizado) = true;
		|||||150+++++
		this.(nombreCampoCapitalizado) = 0;
		|||||160+++++
		this.(nombreCampoCapitalizado) = DateTime.Today;
		|||||170+++++

        }



        public (nombreTabla)ParamGenerated(long? empresaid, long? sucursalid|||||200+++++
    				,(tipoCampoLenguaje) (nombreCampoCapitalizado)|||||300+++++
    				,(tipoCampoLenguaje)? (nombreCampoCapitalizado)|||||400+++++
				  ) : base(empresaid, sucursalid)
        {
|||||410+++++
		this.(nombreCampoCapitalizado) = (nombreCampoCapitalizado);
|||||420+++++
        }


|||||500+++++
    public (tipoCampoLenguaje) (nombreCampoCapitalizado) { get; set; }  
|||||600+++++
    public (tipoCampoLenguaje)? (nombreCampoCapitalizado) { get; set; }  
|||||700+++++



  }
}

!!!!!
100;0;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR
110;1;0;IGNORAR;decimal,double,Boolean,Int64,Int32,Int16,DateTime;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;IGNORAR;CHECKBOX;IGNORAR;ESBASE,ESCOMPLEMENTARIO
120;1;0;IGNORAR;decimal,double,Boolean,Int64,Int32,Int16,DateTime;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;CHECKBOX;IGNORAR;IGNORAR;ESBASE,ESCOMPLEMENTARIO
130;1;0;decimal,double;IGNORAR;IGNORAR;VARCHAR,CHAR;IGNORAR;SI;IGNORAR;1;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;IGNORAR;IGNORAR;IGNORAR;ESBASE,ESCOMPLEMENTARIO
140;1;0;Boolean;IGNORAR;IGNORAR;VARCHAR,CHAR;IGNORAR;SI;IGNORAR;1;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;IGNORAR;IGNORAR;IGNORAR;ESBASE,ESCOMPLEMENTARIO
150;1;0;Int64,Int32,Int16;IGNORAR;IGNORAR;VARCHAR,CHAR;IGNORAR;SI;IGNORAR;1;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;IGNORAR;IGNORAR;IGNORAR;ESBASE,ESCOMPLEMENTARIO
160;1;0;DateTime;IGNORAR;IGNORAR;VARCHAR,CHAR;IGNORAR;SI;IGNORAR;1;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;IGNORAR;IGNORAR;IGNORAR;ESBASE,ESCOMPLEMENTARIO
170;0;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR
200;1;0;IGNORAR;IGNORAR;VARCHAR,CHAR;IGNORAR;IGNORAR;SI;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;IGNORAR;IGNORAR;IGNORAR;ESBASE,ESCOMPLEMENTARIO
300;1;0;IGNORAR;IGNORAR;IGNORAR;VARCHAR,CHAR;IGNORAR;SI;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;IGNORAR;IGNORAR;IGNORAR;ESBASE,ESCOMPLEMENTARIO
400;0;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR
410;1;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;IGNORAR;SI;IGNORAR;IGNORAR;IGNORAR;IGNORAR;ESBASE
420;0;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR
600;1;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;SI;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;ESBASE
700;0;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;IGNORAR;0;IGNORAR;IGNORAR;IGNORAR;IGNORAR


