//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=manuel;Initial Catalog=generador;Persist Security Info=True;User ID=s" +
            "a;Password=Twincept")]
        public string generadorConnectionString {
            get {
                return ((string)(this["generadorConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=localhost;initial catalog=\"G:\\Documents and Settings\\manuel2\\Mis docu" +
            "mentos\\newdb\\NEWDATABASE.FDB\";user id=sysdba;password=masterkey")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=localhost;initial catalog=C:\\IposProject\\IposRopa\\Ipos\\iPos\\bin\\Debug" +
            "\\sampdata\\iposdb.fdb;user id=sysdba;password=masterkey")]
        public string ConnectionIpos {
            get {
                return ((string)(this["ConnectionIpos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=localhost;initial catalog=\"C:\\Documents and Settings\\manuel\\Mis docum" +
            "entos\\Visual Studio 2008\\Projects\\ipos\\iPos\\bin\\Debug\\sampdata\\iposdb\";user id=s" +
            "ysdba;password=masterkey")]
        public string iposdb2 {
            get {
                return ((string)(this["iposdb2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://199.89.53.90/iposwebservice/Service1.asmx")]
        public string iPos_com_server_ipos_Service1 {
            get {
                return ((string)(this["iPos_com_server_ipos_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kikoleria.servebeer.com:8082/iposwebservice/Service1.asmx")]
        public string iPos_com_servebeer_kikoleria_Service1 {
            get {
                return ((string)(this["iPos_com_servebeer_kikoleria_Service1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LinkDialogURLs {
            get {
                return ((string)(this["LinkDialogURLs"]));
            }
            set {
                this["LinkDialogURLs"] = value;
            }
        }
    }
}
